# Generated by Django 4.2.5 on 2023-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slot1_remaining_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='article',
            name='slot2_remaining_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='article',
            name='slot3_remaining_count',
            field=models.IntegerField(default=20),
        ),
    ]
